### ISSUE TITLE
Duplication of Publishers and Locations between MYshort and MYabrv

### ISSUE THREAD

**Issue by pmbittner** [tthuem/BibTags#20]
All publishers and locations are duplicated between MYshort and MYabrv. They even seem to be the very same. I propose to extract this commonality into a `publishers.bib`. What do you think?

**Comment by tthuem** [comment]
This is a breaking change for hundreds of papers and requires a further import for every single use. I prefer to keep this duplication. Should be easier to manage as there is a 1:1 correspondence of lines in both files.

**Comment by pmbittner** [comment]
Ok, I see. Better don't tell anyone that we practice clone-and-own for legacy reasons. :P

**Comment by tthuem** [comment]
Paul, we practice managed code clones here! Even though the management is not automated at all... 😃

**Comment by h3ssto** [comment]
MYshort is a generated file (at my end), so this causes 0 problems.
